import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { UserProvider } from '../components/user/UserContext';
import { CurrentUserBadge } from '../components/user/CurrentUserBadge';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <UserProvider>
          <Header />
          <div className="flex-1 w-full pb-24 sm:pb-0">{children}</div>
          <MobileNav />
        </UserProvider>
      </body>
    </html>
  );
}

import Link from 'next/link';

function Header() {
  return (
    <header className="w-full flex items-center justify-between px-4 py-2 border-b bg-background/80 backdrop-blur sticky top-0 z-40">
      <Link href="/" className="font-bold">
        Ogiri Battle
      </Link>
      <nav className="hidden sm:flex gap-4 text-sm">
        <Link href="/scoreboard">Score</Link>
        <Link href="/archive">Archive</Link>
        <Link href="/jokes/new">Post</Link>
        <Link href="/users/new">User+</Link>
        <Link href="/auth">Auth</Link>
      </nav>
      <div className="hidden sm:block ml-4">
        <CurrentUserBadge />
      </div>
    </header>
  );
}

function MobileNav() {
  return (
    <nav className="sm:hidden fixed bottom-0 left-0 right-0 flex justify-around items-center border-t bg-background/90 backdrop-blur py-2 text-[10px] pb-[calc(env(safe-area-inset-bottom))]">
      <Link href="/scoreboard">Score</Link>
      <Link href="/archive">Archive</Link>
      <Link href="/jokes/new">Post</Link>
      <CurrentUserBadge />
    </nav>
  );
}
